# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base_octree
  - /dataset: colmap
  - /initialization: colmap
  - /render: 3dgrt
  - _self_

# overwrite of default parameters
val_frequency: 999999 # never validate
lod: True
n_iterations: 40000

strategy:
  prune_scale:
    frequency: 100
    start_iteration: 1000
    end_iteration: 25000
    threshold: 1.0