# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base_octree
  - /dataset: nerf
  - /initialization: random
  - /render: 3dgrt
  - _self_

# overwrite of default parameters
val_frequency: 999999 # never validate
lod: True
n_iterations: 40000

strategy:
  prune_scale:
    frequency: 100
    start_iteration: 2000
    end_iteration: 25000
    threshold: 0.9
  densify:
    large_mask: false
  prune:
    start_iteration: 2000

with_gui: False
path: data/MatrixCity/pose/block_all
out_dir: results/kcgs/MatrixCity
experiment_name: ver3_1-matrixcity

export_ingp:
  enabled: false

export_usdz:
  enabled: false


dataset:
  downsample_factor: 1

model:
  visible_threshold: 0.01