# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base_gs
  - /dataset: colmap
  - /initialization: colmap
  - /render: 3dgrt
  - _self_
  
# overwrite of default parameters
val_frequency: 999999 # never validate
lod: True
n_iterations: 30000

export_ingp:
  enabled: false

with_gui: False
path: data/mipnerf360/counter
out_dir: results/lod/dev/0603/ckpt
experiment_name: initialization-0603

dataset:
  downsample_factor: 4