# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base_octree
  - /dataset: colmap
  - /initialization: colmap
  - /render: 3dgrt
  - _self_
  
# overwrite of default parameters
val_frequency: 999999 # never validate
lod: True
n_iterations: 30000

export_ingp:
  enabled: false

with_gui: True
path: data/mipnerf360/garden
out_dir: results/lod/dev/0606/ckpt
experiment_name: density-0606

dataset:
  downsample_factor: 4