# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base_gs
  - /dataset: colmap
  - /initialization: point_cloud
  - /render: 3dgrt
  - _self_
  
# overwrite of default parameters
val_frequency: 999999 # never validate
lod: False
n_iterations: 0

export_ingp:
  enabled: false

gui: False
path: data/mipnerf360/garden
out_dir: results/lod/benchmark/0521/ckpt
experiment_name: 3dgs-3dgrt
initial_ply: '../dataset/ply-files/3dgs/garden.ply'
dataset:
  downsample_factor: 4