# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base_gs
  - /dataset: nerf
  - /initialization: random
  - /render: 3dgrt
  - _self_
  
# overwrite of default parameters
val_frequency: 999999 # never validate
lod: False
n_iterations: 60000

export_ingp:
  enabled: false

with_gui: False
path: data/MatrixCity/pose/block_all
out_dir: results/lod/city/0526/block_all
experiment_name: 3dgrt-3dgrt-60000
dataset:
  downsample_factor: 1