# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base_octree
  - /dataset: nerf
  - /initialization: initial_point_cloud
  - /render: 3dgrt
  - _self_
  
# overwrite of default parameters
val_frequency: 999999 # never validate
lod: True
n_iterations: 60000

export_ingp:
  enabled: False

with_gui: False
path: data/MatrixCity/pose/block_all
out_dir: results/lod/city/0606/block_all
experiment_name: octree-3dgrt-60000
dataset:
  downsample_factor: 4
