# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base_gs
  - /dataset: colmap
  - /initialization: colmap
  - /render: 3dgrt
  - _self_

# overwrite of default parameters
val_frequency: 999999 # never validate
experiment_name: garden
n_iteration: 30000
dataset:
  downsample_factor: 4
out_dir: runs
path: data/mipnerf360/garden
# with_gui: True